### PR TITLE
[Bug]: Hero Image Not Responsive on Mobile

### LINKED ISSUE #8: [bug]:  Hero Image Not Responsive on Mobile Devices
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

At around 1561 width it starts covering the cta entirely till the mobile devices
This is the same issue for this repo on https://github.com/keploy/keploy/issues/1537#issue-2125771455

### Steps to reproduce

image
image

### Environment

None

### Version

Cloud

### PR DESCRIPTION
**Pull request by shreyashrpawar**
# Pull Request Template

## Description
KROC leaderboard PR [#18](https://github.com/keploy/.github/pull/18)

The Hero image is aligning with other elements on mobile devices. So used the css queries to solve this issue.

Fixes #8 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested the change on the mobile device itself. So, the issue will be solved effectively.

## Additional Context (Please include any Screenshots/gifs if relevant)
Visible page on mobile:
keploy's writers

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review

### CODE REVIEW

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
LGTM! But it would be nice if you could share a short video by demonstrating that it's now fully responsive, using the developer tools!

**Comment by shreyashrpawar** [comment]
Here is the short video demonstrating that it's now fully responsive.

https://github.com/user-attachments/assets/5f3378cc-f266-4179-9ebf-1caf32004cd4

@Swpn0neel Kindly check it now

**Comment by Swpn0neel** [comment]
Great! Kindly fix the DCO check:

- Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
- In your local branch, run: git rebase HEAD~3 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin main

**Comment by shreyashrpawar** [comment]
Thanks. Fixed the DCO check

**Comment by shreyashrpawar** [comment]
KROC leaderboard PR [#18](https://github.com/keploy/.github/pull/18)

**Pull request merged**
